config/routes.rb
Rails.application.routes.draw do

  # devise_for :users 

  # resources :posts 

  get '/about/trungtran', to: 'profiles#about'
  
  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true, length: {minimum: 5}
	validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!, except: [:index, :show]

	def index 
		@posts = Post.all.order('created_at DESC')
	end 


	def new 
		@post = Post.new
	end 


	def create 
		@post = Post.new(post_params) 
		if 
			@post.save 
			flash[:success] = "Create new post successfull!"
			redirect_to @post
		else
			render "new"
		end
	end 


	def edit 
		@post = Post.find(params[:id])
	end 


	def update 
		@post = Post.find(params[:id])
		if @post.update(params[:post].permit(:title, :description))
			redirect_to @post
		else
			render "edit"
		end 
	end 


	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end 


	def show 
		@post = Post.find(params[:id])
	end 

	private 
	def post_params
		params.require(:post).permit(:title, :description)		
	end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	def index 
	end 

	def new 
	end 

	def create 
	end 

	def edit 
	end 

	def destroy
	end 

	def update 
	end 

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Tran Trung</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
	
	<%= favicon_link_tag 'favicon.ico' %>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<script type="text/javascript">

      // Menu-toggle button

      $(document).ready(function() {
            $(".menu-icon").on("click", function() {
                  $("nav ul").toggleClass("showing");
            });
      });

      // Scrolling Effect

      $(window).on("scroll", function() {
            if($(window).scrollTop()) {
                  $('nav').addClass('black');
            }

            else {
                  $('nav').removeClass('black');
            }
      })

      </script>

  <body>
	
    <%= yield %>

    <footer>
		<div class="center-foot">
			<div class="icon">
			<ul>	
			<li><a href="https://www.facebook.com/trantrung1512"><i class="fa fa-facebook-official" aria-hidden = "true"></i></a> </li>
			<li><a href="https://www.instagram.com/trung151224/"><i class="fa fa-instagram" aria-hidden = "true"></i></a> </li>
			<li><a href="https://github.com/trungpro152224"><i class="fa fa-github" aria-hidden = "true"></i></a> </li>
			<li><a href="https://twitter.com/trung151224"><i class="fa fa-twitter" aria-hidden = "true"></i></a> </li>
			<li><a href="https://www.youtube.com/channel/UCBmyulDy1py6HAWPg0DvyqQ?view_as=subscriber"><i class="fa fa-youtube" aria-hidden = "true"></i></a> </li>
			</ul>
			</div>
			<p> © 2018 Trung Tran Huu • All rights reserved. </p>
		</div>
</footer>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

	<% if @post.errors.full_messages.any? %>
  <% @post.errors.full_messages.each do |error_message| %>
    <%= error_message if @post.errors.full_messages.first == error_message %> <br />

  <% end %>
<% end %>

<p>
	<%= f.label :title %>
	<br>
	<%= f.text_field :title %>
</p>

<p>
	<%= f.label :description %> 
	<br>
	<%= f.text_area :description %> 
</p>

<p>
	<%= f.button :submit, :class => "btn btn-warning btn-small", :label => "Save Changes" %>

	<%= submit_tag("Refresh", { :name => 'reset', :id => 'reset_button', :type => "reset", :class => 'btn btn-default'}) %>
</p>

 <% end %>

app/views/posts/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	
	<div class="wrapper">
	<div class="header4">
		<nav>
		
			<div class="logo"> TrungTH </div>
			<div class="menu-icon">
			 <span class="glyphicon glyphicon-fire" aria-hidden = "true"></span>
		</div>
			<ul>
				<li><%= link_to "New" ,new_post_path, :class=>"login"%></li>

				<li><%= link_to "Back", posts_path, :class=>"login"%></li>

				<% if user_signed_in? %>
				  <li>
				  <%= link_to('Log out', destroy_user_session_path, method: :delete, :class=>"login") %>  

				  
				  </li>
				<% else %>
				  <li>
				  <%= link_to('Log in', new_user_session_path, :class=>"login")  %>  
				  </li>
				  
				<% end %>
			</ul>
		</nav>
	</div>
	</div>


	<h1 class="new-post-wrapper"> EDIT POST</h1>
	
	<%= render 'form' %>

</body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>


<body>
<!-- header -->

	<div class="wrapper">
	<div class="header1">
		<nav>
		
			<div class="logo"> TrungTH </div>
			<div class="menu-icon">
			 <span class="glyphicon glyphicon-fire" aria-hidden = "true"></span>
		</div>
			<ul>
				<li><%= link_to "New" ,new_post_path, :class=>"login"%></li>

				<li><%= link_to "Home", root_path, :class=>"login"%></li>

				<% if user_signed_in? %>
				  <li>
				  <%= link_to('Log out', destroy_user_session_path, method: :delete, :class=>"login") %>  

				  </li>
				<% else %>
				  <li>
				  <%= link_to('Log in', new_user_session_path, :class=>"login")  %>  
				  </li>

				<% end %>

			</ul>
		</nav>
	</div>
	</div>


<h1> SHOW ALL POST</h1>

<% @posts.each do |post| %>
<div class="wrapper">
	<h2 class="title"><%= link_to post.title, post %> </h2>
	<p class="date"> <%= post.created_at.strftime("%B, %d, %Y") %> 
	</p>
</div>
<% end %>

</body>
</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>

<body>


	<div class="wrapper">
	<div class="header2">
		<nav>
		
			<div class="logo"> TrungTH </div>
			<div class="menu-icon">
			 <span class="glyphicon glyphicon-fire" aria-hidden = "true"></span>
		</div>
			<ul>
				<li><%= link_to "Home" ,root_path, :class=>"login"%></li>

				<li><%= link_to "Posts", posts_path, :class=>"login"%></li>

				<% if user_signed_in? %>
				  <li>
				  <%= link_to('Log out', destroy_user_session_path, method: :delete, :class=>"login") %>  

				   

				  </li>
				<% else %>
				  <li>
				  <%= link_to('Log in', new_user_session_path, :class=>"login")  %>  
				  </li>
				
				<% end %>
			</ul>
		</nav>
	</div>
	</div>

<h1 class="new-post-wrapper"> NEW POST</h1>
	<%= render 'form' %>


</body>
</html>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>


<div class="wrapper">
	<div class="header3">
		<nav>
		
			<div class="logo"> TrungTH </div>
			<div class="menu-icon">
			 <span class="glyphicon glyphicon-fire" aria-hidden = "true"></span>
		</div>
			<ul>
				<li><%= link_to 'Edit', edit_post_path(@post),:class=>"login" %></li>

				<li><%= link_to 'Destroy', post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, :class=>"login" %>
				</li>
				
				<li><%= link_to "Back", root_path, :class=>"login"%></li>

				<% if user_signed_in? %>
				  <li>
				  <%= link_to('Log out', destroy_user_session_path, method: :delete, :class=>"login") %>  

				  </li>
				<% else %>
				  <li>
				  <%= link_to('Log in', new_user_session_path, :class=>"login")  %>  
				  </li>

				<% end %>
				
			</ul>
		</nav>
	</div>
	</div>

<h1>SHOW POST</h1>

<h2 class="title">
<%= @post.title %> 
</h2>

<p class="description">
	<%= @post.description %>
</p>

<p class="time">
	Submited <%= time_ago_in_words(@post.created_at) %> Ago 

</p>

</body>
</html>

app/views/profiles/about.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<script src="files/theme/jquery.easypiechart.min.js"></script>

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<div class="wrapper">
	<div class="header5">
		<nav>
		
			<div class="logo"> TrungTH </div>
			<div class="menu-icon">
			 <span class="glyphicon glyphicon-fire" aria-hidden = "true"></span>
		</div>
			<ul>
				<li><%= link_to "Home" ,root_path, :class=>"login"%></li>

				<li><%= link_to "Posts","#", :class=>"login"%></li>

			
				  <li>
				  <%= link_to('Log in',"#" , :class=>"login")  %>  
				  </li>

			
			</ul>
		</nav>
	</div>
	</div>

<marquee>Failure is the condiment that gives success its flavor!   - (Truman Capote) - </marquee>


<div id ="wrapper-body">

<!-- image-profiles -->
<div class="about-profile">
    <%=image_tag("avatar.jpg", alt: "Avatar", :class => "style-image")%>
	<div class="hover-image-change-text"> 
	</div>

</div>


<!-- contact -->
<div class="contact">

<h1>Contact</h1>
	<i class="material-icons" style="font-size:25px">person</i>
	<h3 class="name"> Full Name</h3>
	<p class="name">Trần Hữu Trung</p>

	<i class="fa fa-birthday-cake" style="font-size:18px"></i>
	<h3 class="birth"> Date Of Birth</h3>
	<p class="birth">Dec 15, 1995</p>
	
	<i class="fa fa-venus-mars" style="font-size:25px;"></i>
	<h3 class="gender"> Gender</h3>
	<p class="gender">Male</p>

	<i class="material-icons">ring_volume</i>
	<h3 class="phone"> Phone Number</h3>
	<p class="phone"> +84 0978 860 750</p>
	
	<i class="material-icons">mail</i>
	<h3 class="gmail"> Gmail</h3>
	<p class="gmail">trungpro151224@gmail.com</p>

	<i class="material-icons" style="font-size:24px">person_pin_circle</i>
	<h3 class="address"> Address</h3>
	<p class="address">915/15 Le Van Luong str., Dist .Nha Be, Ho Chi Minh City</p>

	<i class="fa fa-facebook-square" style="font-size:24px"></i>
	<h3 class="face"> Facebook</h3>
	<br>
	<a href="https://www.facebook.com/trantrung1512" class="face">https://www.facebook.com/trantrung1512</a>

</div>


<!-- education -->
<div class="education">

	<h1>Education</h1>


	<table>
		<tr> 
			<td><p><strong>2000-2005 </strong></p>  </td>
			<td> <p>An Phu Trung Primary School - Ben Tre</p> </td>
			</tr>

			<tr>
			<td><p><strong>2005-2009 </strong></p>  </td>
			<td> <p>An Phu Trung Junior High School - Ben Tre</p> </td>
			</tr>

			<tr>
			<td><p><strong>2010-2013 </strong></p>  </td>
			<td> <p>Phan Thanh Gian High School - Ben Tre</p> </td>
			</tr>

			<tr>
			<td><p><strong> 2013-now </strong></p>  </td>
			<td> <p>Ton Duc Thang University - Ho Chi Minh </p> </td>
			</tr>

	</table>

</div>


<!-- skills -->
<div class="skills-all">

	<h1 class="skill-title"> Software Skills</h1>

		<div class="skills-box">

			<p>HTML5, CSS3</p>
			<div class="progress">
  <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 90%">
    <span>90% Complete</span>
  </div>
</div>
		</div>	



	<div class="skills-box">	
			<p>C#</p>
			<div class="progress">
  <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 70%">
    <span>70% Complete</span>
  </div>
</div>
	</div>

		<div class="skills-box">
		
			<p>RUBY ON RAILS</p>
			<div class="progress">
  <div class="progress-bar progress-bar-warning progress-bar-striped" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 75%">
    <span>75% Complete</span>
  </div>
	</div>
		</div>	

		<div class="skills-box">
		
			<p>BOOTSTRAP</p>
			<div class="progress">
  <div class="progress-bar progress-bar-muted progress-bar-striped" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 70%">
    <span>70% Complete</span>
  </div>
</div>
		</div>	

	<div class="skills-box">
		
			<p>JAVASCRIPT</p>
			<div class="progress">
  <div class="progress-bar progress-bar-danger progress-bar-striped" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 65%">
    <span >65% Complete </span>
  </div>
</div>

		</div>	

</div>




<!-- languages -->
<div class="languages">

	<h1>Languages</h1>

<div class="language-bar">

	<div class="language-bar-listen">
	 <p>Listening</p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:45%">45%</div>
          </div>
		</div>

		<div class="language-bar-speak"> 
          <p>Speaking</p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:60%">
              <div class="w3-center w3-text-white">60%</div>
            </div>
          </div>
          </div>
		

		<div class="language-bar-read">
          <p>Reading</p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:65%">65%</div>
          </div>
		</div>


		<div class="language-bar-write">
          <p>Writing</p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:70%">
              <div class="w3-center w3-text-white">70%</div>
            </div>
          </div>
          </div>
        </div>

</div>

<!-- about me -->
<div class="about-me">

		<h1>About Me</h1>

	<div class="moralism">
		<strong>1. Close - Mouthed</strong>
		<p>= >>>> But many feelings !!!</p>
	</div>

	<div class="moralism">
		<strong>2. Hasty</strong>
		<p>= >>>> But good stomach !!!</p>
	</div>

	<div class="moralism">
		<strong>3. Dry</strong>
		<p>= >>>> But honestly !!!!</p>
	</div>

	<div class="moralism">
		<strong>4. Silence </strong>
		<p>= >>>> But I do care !!!</p>
	</div>

	<div class="moralism">
		<strong>5. Cold</strong>
		<p>= >>> But love true !!!</p>
	</div>
</div>


<!-- interests -->
<div class="interests">
	
	<h1>Interests</h1>

	<div class="interest-sport">
		<i class="material-icons" style="font-size:24px;color:red">rowing</i>
			<h2>Sport</h2>
		<%=image_tag("image-sport.jpeg", alt: "Avatar", :class => "image-sport")%>
		</div>

	<div class="interest-travel">
		<i class="fa fa-motorcycle" style="font-size:18px;color:red"></i>
		<h2>Travel</h2>
		<%=image_tag("image-travel.jpeg", alt: "Avatar", :class => "image-travel")%>
		</div>

	<div class="interest-code">
		<i class="material-icons" style="font-size:24px;color:red">keyboard</i>
		<h2>Code</h2>
		<%=image_tag("image-code.jpg", alt: "Avatar", :class => "image-code")%>
		</div>

	
	<div class="interest-music">
		<i class="material-icons" style="font-size:24px;color:red">headset_mic</i>
		<h2 class="music-box">Music</h2>
		<%=image_tag("image-music.jpeg", alt: "Avatar", :class => "image-music")%>
		</div>

</div>

</div>

</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title> Blog Tran Trung </title>

</head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<body>
<!-- header -->

	<div class="wrapper">
	<header>
		<nav>
			
			<div class="logo"> TrungTH </div>
			

			<div class="menu-icon">
			 <span class="glyphicon glyphicon-fire" aria-hidden = "true"></span>
		</div>
			<ul>
				<li> <%= link_to "posts" ,"#", :class=>"login"%></li>

				<li> <%= link_to "About", about_trungtran_path, :class=>"login"%></li>
				
				  <li>
				  <%= link_to('Log in', "#", :class=>"login")  %>  
				  </li>

			</ul>
		</nav>
	</header>
	</div>

	<div class="content">
	
	<p class="bold-tht">Trần Hữu Trung</p>
	<p> Đây là cái tên mà ba mẹ đã đặt cho tôi. Quê hương xứ dừa mà tôi đã được gắn bó, được sinh ra và lớn lên trong mảnh đất đầy tình thương, mộc mạc của  con người Bến Tre. Lúc nhỏ, tôi là một cậu bé ngoan ngoãn, rất biết vâng lời ba mẹ. Nhiều năm liền đều đạt thành tích tốt trong học tập cũng như các hoạt động ngoại khóa của trường, lớp... </p>

	<p>Câu chuyện bắt đầu từ khi tôi lên đại học. Thật sự mà nói, tôi đã thay đổi rất nhiều trong những năm đó. Từ cấp ba, tôi đã thích về nghề IT (máy tính) nhưng chưa tìm hiểu rõ những dòng code nó khó khăn đến như thế nào? Bắt đầu vào giảng đường đại học, những năm đầu rất suông sẻ cho tới khi bước vào chuyên ngành mình học. Tôi cảm thấy rất áp lực và dường như tự hỏi: Liệu mình có chọn sai ngành? Liệu mình có nên tiếp tục về nghề dev này nữa không?"  Cứ thế, việc học thì càng ngày càng sa sút, tôi bắt đầu lao vào game online và dường như không thể tách rời nó mỗi khi về nhà với chiếc máy tính trên bàn.  </p>
	
	<p>
	Thử thách càng ngày càng nhiều, áp lực cứ thế mà đè nặng lên vai!  23 tuổi đầu, với đôi bàn tay trắng tôi cảm thấy rất tự ti với bản thân và càng ngày càng sống khép mình lại. 
	</p>

	<p>
	"Failure is the condiment that gives success its flavor". 
	</p>

	<p>
	"Thất bại là gia vị tạo nên sự ngon miệng của thành công".	</p>

	<p class="author">
	(Truman Capote)  
	</p>

	<p>
	Thành công là điều mà mỗi con người trong chúng ta đều mong muốn! Với tôi, thành công lớn nhất đó là phải biết tự mình đứng lên sau những thất bại và coi đó là một bài học quý giá để mình trưởng thành hơn. Tôi bắt đầu làm quen với những dòng code, tìm tòi những tài liệu trên mạng nói về lập trình. bắt đầu bỏ dần game online và tập tành street workout (môn thể thao đường phố yêu thích của tôi)... 
	</p>

	<p>
	 "Cần cù bù thông minh" Tôi nghĩ, không có việc gì mà chúng ta không làm được nếu tự mình từ bỏ nó. Không có sự thành công nào mà không đánh đổi bằng mồ hôi, nước mắt và sự đau đớn. Hãy đặt cho mình những mục tiêu cao hơn, vĩ đại hơn và tự nhủ với lòng rằng "I can do it, I will do it...  ->  Yes, I did it !!!" 
 
	</p>
	</div> 
    </body>
</html>